# === Entity Group Playbook ===

EntityGroupType: cmd-partials
DisplayName: "Command + Handler + Partial Service"
Description: >
  Standard CLI entry point composed of:
    - a CLI command definition class
    - a command handler
    - a service class split across partials
  This pattern drives orchestrated operations such as Docker, Redis, GitHub, and deployment tooling.

AppliesTo: cli

# === Namespace Resolution ===

TargetRootNamespace: "{solution}"

# === Core Pattern Definitions ===

Patterns:
  Command: "{solution}.commands.{target}_Command"
  CommandHandler: "{solution}.commandhandlers.{target}_CommandHandler"
  ServiceOrchestrator: "{solution}.services.{target}.{target}Service"
  ServicePartials: "{solution}.services.{target}.* (excluding {target}Service)"

# === Entry Point ===

EntryMethod: "ImportAsync"  # Can be overridden in context generation

# === Test Output Path ===

OutputTestFolder: "{solution}.CLI.Tests/Services/{target}/"

# === Validation Rules ===

Validation:
  RequireCommand: true
  RequireCommandHandler: true
  RequireServicePartial: true
  RequireEntryMethod: true

# === Test Generation Rules ===

TestGeneration:
  OrchestratorTestClass: "{target}ServiceTests"
  PartialMethodTestClassPattern: "{methodName}Tests"
  TestPatternSource: "Testing.CLI.TestSuitePlaybook.md"
  ApplyFixes:
    - F01
    - F03
    - F05
    - F06
    - F07
    - F13
    - F15
    - F16
